# Generated by Django 4.0.2 on 2022-02-20 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnos',
            fields=[
                ('diag_id', models.IntegerField(primary_key=True, serialize=False)),
                ('diag_date', models.DateField()),
                ('diag_diagnosis', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('ex_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ex_question', models.CharField(max_length=200)),
                ('ex_result', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='OprateExamination',
            fields=[
                ('ope_ex_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ope_ex_date', models.DateField()),
                ('ope_ex_answer', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='OprateRisk',
            fields=[
                ('ope_risk_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ope_risk_date', models.DateField()),
                ('ope_risk_answer', models.DecimalField(decimal_places=10, max_digits=20)),
                ('ope_risk_result', models.DecimalField(decimal_places=10, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='PeriodDate',
            fields=[
                ('per_date_id', models.IntegerField(primary_key=True, serialize=False)),
                ('per_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('pho_id', models.IntegerField(primary_key=True, serialize=False)),
                ('pho_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('pred_id', models.IntegerField(primary_key=True, serialize=False)),
                ('pred_feature1', models.DecimalField(decimal_places=10, max_digits=20)),
                ('pred_feature2', models.DecimalField(decimal_places=10, max_digits=20)),
                ('pred_feature3', models.DecimalField(decimal_places=10, max_digits=20)),
                ('pred_feature4', models.DecimalField(decimal_places=10, max_digits=20)),
                ('pred_feature5', models.DecimalField(decimal_places=10, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='RiskCalculator',
            fields=[
                ('risk_id', models.IntegerField(primary_key=True, serialize=False)),
                ('risk_question', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('us_id', models.IntegerField(primary_key=True, serialize=False)),
                ('us_firstname', models.CharField(max_length=50)),
                ('us_lastname', models.CharField(max_length=50)),
                ('us_email', models.CharField(max_length=50)),
                ('us_birthdate', models.DateField(max_length=50)),
                ('us_rathe', models.CharField(max_length=50)),
                ('phone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Hawaapp.phone', unique=True)),
            ],
        ),
    ]
